/* 
*  All loaders are made using the following website: https://loading.io
*/

const loaders = {
  loader_type: {
    network: `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" width="100" height="100%" style="shape-rendering: auto; display: block; background: rgba(255, 255, 255, 0);">
                <g>
                  <circle cx="28" cy="75" r="11" fill="#000000">
                    <animate attributeName="fill-opacity" repeatCount="indefinite" dur="1s" values="0;1;1" keyTimes="0;0.2;1" begin="0s"/>
                  </circle>
                  <path d="M28 47A28 28 0 0 1 56 75" fill="none" stroke="#545454" stroke-width="10">
                    <animate attributeName="stroke-opacity" repeatCount="indefinite" dur="1s" values="0;1;1" keyTimes="0;0.2;1" begin="0.1s"/>
                  </path>
                  <path d="M28 25A50 50 0 0 1 78 75" fill="none" stroke="#b3b3b3" stroke-width="10">
                    <animate attributeName="stroke-opacity" repeatCount="indefinite" dur="1s" values="0;1;1" keyTimes="0;0.2;1" begin="0.2s"/>
                  </path>
                <g/>
                </g><!-- [ldio] generated by https://loading.io -->
              </svg>`,
    bubble: `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" width="100%" height="100%" style="shape-rendering: auto; display: block; background: transparent;"><g><g transform="translate(68,50)">
              <g transform="rotate(0)">
              <circle cx="0" cy="0" r="4" fill="#000000" fill-opacity="1">
                <animateTransform attributeName="transform" type="scale" begin="-0.6386861313868613s" values="1.68 1.68;1 1" keyTimes="0;1" dur="0.7299270072992701s" repeatCount="indefinite"/>
                <animate attributeName="fill-opacity" keyTimes="0;1" dur="0.7299270072992701s" repeatCount="indefinite" values="1;0" begin="-0.6386861313868613s"/>
              </circle>
              </g>
              </g><g transform="translate(62.72792206135786,62.72792206135786)">
              <g transform="rotate(45)">
              <circle cx="0" cy="0" r="4" fill="#000000" fill-opacity="0.875">
                <animateTransform attributeName="transform" type="scale" begin="-0.5474452554744526s" values="1.68 1.68;1 1" keyTimes="0;1" dur="0.7299270072992701s" repeatCount="indefinite"/>
                <animate attributeName="fill-opacity" keyTimes="0;1" dur="0.7299270072992701s" repeatCount="indefinite" values="1;0" begin="-0.5474452554744526s"/>
              </circle>
              </g>
              </g><g transform="translate(50,68)">
              <g transform="rotate(90)">
              <circle cx="0" cy="0" r="4" fill="#000000" fill-opacity="0.75">
                <animateTransform attributeName="transform" type="scale" begin="-0.45620437956204374s" values="1.68 1.68;1 1" keyTimes="0;1" dur="0.7299270072992701s" repeatCount="indefinite"/>
                <animate attributeName="fill-opacity" keyTimes="0;1" dur="0.7299270072992701s" repeatCount="indefinite" values="1;0" begin="-0.45620437956204374s"/>
              </circle>
              </g>
              </g><g transform="translate(37.27207793864214,62.72792206135786)">
              <g transform="rotate(135)">
              <circle cx="0" cy="0" r="4" fill="#000000" fill-opacity="0.625">
                <animateTransform attributeName="transform" type="scale" begin="-0.36496350364963503s" values="1.68 1.68;1 1" keyTimes="0;1" dur="0.7299270072992701s" repeatCount="indefinite"/>
                <animate attributeName="fill-opacity" keyTimes="0;1" dur="0.7299270072992701s" repeatCount="indefinite" values="1;0" begin="-0.36496350364963503s"/>
              </circle>
              </g>
              </g><g transform="translate(32,50)">
              <g transform="rotate(180)">
              <circle cx="0" cy="0" r="4" fill="#000000" fill-opacity="0.5">
                <animateTransform attributeName="transform" type="scale" begin="-0.2737226277372263s" values="1.68 1.68;1 1" keyTimes="0;1" dur="0.7299270072992701s" repeatCount="indefinite"/>
                <animate attributeName="fill-opacity" keyTimes="0;1" dur="0.7299270072992701s" repeatCount="indefinite" values="1;0" begin="-0.2737226277372263s"/>
              </circle>
              </g>
              </g><g transform="translate(37.27207793864214,37.27207793864214)">
              <g transform="rotate(225)">
              <circle cx="0" cy="0" r="4" fill="#000000" fill-opacity="0.375">
                <animateTransform attributeName="transform" type="scale" begin="-0.18248175182481752s" values="1.68 1.68;1 1" keyTimes="0;1" dur="0.7299270072992701s" repeatCount="indefinite"/>
                <animate attributeName="fill-opacity" keyTimes="0;1" dur="0.7299270072992701s" repeatCount="indefinite" values="1;0" begin="-0.18248175182481752s"/>
              </circle>
              </g>
              </g><g transform="translate(50,32)">
              <g transform="rotate(270)">
              <circle cx="0" cy="0" r="4" fill="#000000" fill-opacity="0.25">
                <animateTransform attributeName="transform" type="scale" begin="-0.09124087591240876s" values="1.68 1.68;1 1" keyTimes="0;1" dur="0.7299270072992701s" repeatCount="indefinite"/>
                <animate attributeName="fill-opacity" keyTimes="0;1" dur="0.7299270072992701s" repeatCount="indefinite" values="1;0" begin="-0.09124087591240876s"/>
              </circle>
              </g>
              </g><g transform="translate(62.72792206135785,37.27207793864214)">
              <g transform="rotate(315)">
              <circle cx="0" cy="0" r="4" fill="#000000" fill-opacity="0.125">
                <animateTransform attributeName="transform" type="scale" begin="0s" values="1.68 1.68;1 1" keyTimes="0;1" dur="0.7299270072992701s" repeatCount="indefinite"/>
                <animate attributeName="fill-opacity" keyTimes="0;1" dur="0.7299270072992701s" repeatCount="indefinite" values="1;0" begin="0s"/>
              </circle>
              </g>
              </g><g/></g><!-- [ldio] generated by https://loading.io --></svg>`,
    search: `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" width="100%" height="100%" style="shape-rendering: auto; display: block; background: rgba(255, 255, 255, 0);"><g><g transform="translate(50 50)">
              <g transform="scale(0.68)">
                <g transform="translate(-50 -50)">
                  <g>
                    <animateTransform attributeName="transform" type="translate" repeatCount="indefinite" dur="1.0869565217391304s" values="-20 -20;20 -20;0 20;-20 -20" keyTimes="0;0.33;0.66;1"/>
                    <path fill="rgba(70, 223, 240, 0)" d="M44.19 26.158c-4.817 0-9.345 1.876-12.751 5.282c-3.406 3.406-5.282 7.934-5.282 12.751 c0 4.817 1.876 9.345 5.282 12.751c3.406 3.406 7.934 5.282 12.751 5.282s9.345-1.876 12.751-5.282 c3.406-3.406 5.282-7.934 5.282-12.751c0-4.817-1.876-9.345-5.282-12.751C53.536 28.033 49.007 26.158 44.19 26.158z"/>
                    <path fill="#000000" d="M78.712 72.492L67.593 61.373l-3.475-3.475c1.621-2.352 2.779-4.926 3.475-7.596c1.044-4.008 1.044-8.23 0-12.238 c-1.048-4.022-3.146-7.827-6.297-10.979C56.572 22.362 50.381 20 44.19 20C38 20 31.809 22.362 27.085 27.085 c-9.447 9.447-9.447 24.763 0 34.21C31.809 66.019 38 68.381 44.19 68.381c4.798 0 9.593-1.425 13.708-4.262l9.695 9.695 l4.899 4.899C73.351 79.571 74.476 80 75.602 80s2.251-0.429 3.11-1.288C80.429 76.994 80.429 74.209 78.712 72.492z M56.942 56.942 c-3.406 3.406-7.934 5.282-12.751 5.282s-9.345-1.876-12.751-5.282c-3.406-3.406-5.282-7.934-5.282-12.751 c0-4.817 1.876-9.345 5.282-12.751c3.406-3.406 7.934-5.282 12.751-5.282c4.817 0 9.345 1.876 12.751 5.282 c3.406 3.406 5.282 7.934 5.282 12.751C62.223 49.007 60.347 53.536 56.942 56.942z"/>
                  </g>
                </g>
              </g>
            </g><g/></g>
          <!-- [ldio] generated by https://loading.io --></svg>`
  },
  show: function (load_div, type, message = "Give me some time, I'm working on it...") {
    const loader = this.loader_type[type];
    const toEdit = document.getElementById(load_div);
    toEdit.style.display = 'block';
    const messageHTML = `<p>${message}</p>`;
    toEdit.innerHTML = `<div>${loader}</div>` + messageHTML;
  },
  hide: function (load_div) {
    document.getElementById(load_div).style.display = 'none';
  }
}
